version: '3'
services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000


  celery:
    build: .
    command: celery -A agent worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  redis:
    image: redis:alpine
