# Generated by Django 5.1.1 on 2024-10-02 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_call_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['time']},
        ),
    ]
