# Generated by Django 5.1.1 on 2024-10-02 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_alter_log_options'),
        ('calls', '0003_call_consent_call_customer_name_call_customer_phone'),
    ]

    operations = [
    ]
