# Generated by Django 5.1.1 on 2024-09-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('prompt', models.TextField()),
                ('greeting_message', models.TextField()),
                ('max_tokens', models.IntegerField()),
                ('idle_timeout', models.IntegerField()),
                ('max_idle_messages', models.IntegerField()),
                ('idle_message', models.TextField()),
                ('is_publish', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
