# Generated by Django 5.1.1 on 2024-09-30 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_assistant_created_by'),
        ('config', '0002_twilioconfig_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='config.twilioconfig'),
        ),
    ]
